name = "oreore-net"
main = "src/index.ts"
compatibility_date = "2025-01-01"
workers_dev = false

routes = [
  { pattern = "oreore.net", custom_domain = true },
]

[assets]
directory = "./public"

[[r2_buckets]]
binding = "CERTS"
bucket_name = "oreore-net-certs"
