name: Renew Certificate
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run scripts/renew-cert.ts
        env:
          ACME_EMAIL: kawazzz@gmail.com
          DOMAINS: "*.oreore.net,*.lo.oreore.net,*.localhost.oreore.net"
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_R2_ACCESS_KEY_ID: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
          CF_R2_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_SECRET_ACCESS_KEY }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          R2_BUCKET: oreore-net-certs
